[package]
distribution = "2201.10.0"
org = "ballerinax"
name = "hubspot.marketing.forms"
version = "@toml.version@"
license = ["Apache-2.0"]
authors = ["Ballerina"]
keywords = ["hubspot", "crm", "marketing", "forms"]
repository = "https://github.com/ballerina-platform/module-ballerinax-hubspot.marketing.forms"

[build-options]
observabilityIncluded = true

[platform.java17]
graalvmCompatible = true


